// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7YNAqS86cy3Y_DZnL3tvLZuxifqMicqY',
    appId: '1:146489587725:web:6905fef6dd75d7e4ca3d44',
    messagingSenderId: '146489587725',
    projectId: 'trajan-food-app-98028',
    authDomain: 'trajan-food-app-98028.firebaseapp.com',
    storageBucket: 'trajan-food-app-98028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBghhKM1hSM2WyNTHYuweOwhk77CkbqAcA',
    appId: '1:146489587725:android:510743f28b8261fdca3d44',
    messagingSenderId: '146489587725',
    projectId: 'trajan-food-app-98028',
    storageBucket: 'trajan-food-app-98028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vr7dt6Vp6WF-qiRPI84UKiEPtHnDNq8',
    appId: '1:146489587725:ios:861d4e98701890d8ca3d44',
    messagingSenderId: '146489587725',
    projectId: 'trajan-food-app-98028',
    storageBucket: 'trajan-food-app-98028.appspot.com',
    iosBundleId: 'com.example.trajanFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vr7dt6Vp6WF-qiRPI84UKiEPtHnDNq8',
    appId: '1:146489587725:ios:cd5f397f8baa45d1ca3d44',
    messagingSenderId: '146489587725',
    projectId: 'trajan-food-app-98028',
    storageBucket: 'trajan-food-app-98028.appspot.com',
    iosBundleId: 'com.example.trajanFoodApp.RunnerTests',
  );
}
